### PR TITLE
python doesn't run in this workspace

### PR DESCRIPTION
**Pull request by zmzlois**
python doesn't run but python3 does, edited readme.

### CODE REVIEW

**Comment by fabjanvucina** [comment]
Hi @zmzlois , which version of Daytona were you on when you encountered this issue? You can find the version in the dashboard footer.

**Comment by zmzlois** [comment]
hey @fabjanvucina 
8.77.1

**Comment by fabjanvucina** [comment]
Closing this as I could not reproduce the mentioned issue on a newer version (v8.79.1).
image

**Comment by fabjanvucina** [comment]
Closing this as I could not reproduce the mentioned issue on a newer version (v8.79.1).
image

**Pull request closed without merging**
